#!/bin/bash
[[ "$(uname)" != "Darwin" ]] && { echo "Error: This script can only be run on macOS."; exit 0; }

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew update
brew tap luxmentis/tap https://codeberg.org/luxmentis/homebrew-tap
brew trust luxmentis/tap
brew install xcbeautify xcodes aria2 xcodegen xcede

cd "$(dirname "$0")"
cp lsp.lua $HOME/.config/nvim-code/lua/custom/swift.lua
cp debug.lua $HOME/.config/nvim-debugger/lua/custom/ios.lua
